-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               8.0.35 - MySQL Community Server - GPL
-- Server OS:                    Win64
-- HeidiSQL Version:             12.6.0.6765
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Dumping database structure for dataprocess
CREATE DATABASE IF NOT EXISTS `dataprocess` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;
USE `dataprocess`;

-- Dumping structure for table dataprocess.operational_resource_project
CREATE TABLE IF NOT EXISTS `operational_resource_project` (
  `projectId` varchar(50) NOT NULL,
  `projectName` varchar(50) NOT NULL,
  `divisionId` varchar(50) NOT NULL,
  `displayOrder` int DEFAULT '0',
  `status` bit(1) NOT NULL DEFAULT b'1',
  `template` text,
  `mode` varchar(50) NOT NULL DEFAULT 'Info',
  `templateUploadDate` datetime DEFAULT NULL,
  `clientName` varchar(50) DEFAULT NULL,
  `projectType` varchar(50) DEFAULT NULL,
  `projectManagerId` varchar(50) DEFAULT 'EDRAdmin',
  `poNumber` varchar(50) DEFAULT NULL,
  `poDated` varchar(50) DEFAULT NULL,
  `billingCycle` varchar(50) DEFAULT NULL,
  `projectStatus` varchar(50) DEFAULT NULL,
  `deliverables` varchar(50) DEFAULT NULL,
  `modeOfDelivery` varchar(50) DEFAULT NULL,
  `inputReceivingMode` varchar(50) DEFAULT NULL,
  `inputType` varchar(50) DEFAULT NULL,
  `displayInOtherUIProjectList` varchar(50) DEFAULT NULL,
  `totalProjectedWorkVolume` varchar(50) DEFAULT NULL,
  `unitsOfMeasurement` varchar(50) DEFAULT NULL,
  `receivedWorkVolume` varchar(50) DEFAULT NULL,
  `estimatedTotalHours` varchar(50) DEFAULT NULL,
  `plannedNoOfResources` varchar(50) DEFAULT NULL,
  `noOfDaysRequiredToComplete` varchar(50) DEFAULT NULL,
  `bpsStartDate` varchar(50) DEFAULT NULL,
  `bpsPlannedCompletionDate` varchar(50) DEFAULT NULL,
  `clientExpectedCompletionDate` varchar(50) DEFAULT NULL,
  `actualCompletedDate` varchar(50) DEFAULT NULL,
  `createdBy` varchar(50) DEFAULT NULL,
  `createdDate` datetime DEFAULT NULL,
  `modifiedBy` varchar(50) DEFAULT NULL,
  `modifiedDate` datetime DEFAULT NULL,
  PRIMARY KEY (`projectId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

-- Dumping data for table dataprocess.operational_resource_project: ~7 rows (approximately)
INSERT INTO `operational_resource_project` (`projectId`, `projectName`, `divisionId`, `displayOrder`, `status`, `template`, `mode`, `templateUploadDate`, `clientName`, `projectType`, `projectManagerId`, `poNumber`, `poDated`, `billingCycle`, `projectStatus`, `deliverables`, `modeOfDelivery`, `inputReceivingMode`, `inputType`, `displayInOtherUIProjectList`, `totalProjectedWorkVolume`, `unitsOfMeasurement`, `receivedWorkVolume`, `estimatedTotalHours`, `plannedNoOfResources`, `noOfDaysRequiredToComplete`, `bpsStartDate`, `bpsPlannedCompletionDate`, `clientExpectedCompletionDate`, `actualCompletedDate`, `createdBy`, `createdDate`, `modifiedBy`, `modifiedDate`) VALUES
	('Admin', 'Admin', 'Accounts', 7, b'1', '{\r\n   "discardPercentage":1,\r\n   "skipRows":2,\r\n   "columnMetaData":[\r\n      {\r\n         "cellIndex":1,\r\n         "fieldName":"receivedDate",\r\n         "parentCellIndex":1,\r\n         "parentFieldName":"receivedDate"\r\n      },\r\n      {\r\n         "cellIndex":2,\r\n         "fieldName":"workUnitId",\r\n         "parentCellIndex":2,\r\n         "parentFieldName":"workUnitId"\r\n      },\r\n      {\r\n         "cellIndex":3,\r\n         "fieldName":"subCountry",\r\n         "parentCellIndex":3,\r\n         "parentFieldName":"subCountry"\r\n      },\r\n      {\r\n         "cellIndex":4,\r\n         "fieldName":"wuMiles",\r\n         "parentCellIndex":4,\r\n         "parentFieldName":"wuMiles"\r\n      },\r\n      {\r\n         "cellIndex":5,\r\n         "fieldName":"roadType",\r\n         "parentCellIndex":5,\r\n         "parentFieldName":"roadType"\r\n      },\r\n      {\r\n         "cellIndex":6,\r\n         "fieldName":"PRIMARYNONDIVIDEDMOTORWAYS",\r\n         "parentCellIndex":5,\r\n         "parentFieldName":"roadType"\r\n      },\r\n      {\r\n         "cellIndex":7,\r\n         "fieldName":"PRIMARYNONDIVIDEDTRUNK",\r\n         "parentCellIndex":5,\r\n         "parentFieldName":"roadType"\r\n      },\r\n      {\r\n         "cellIndex":8,\r\n         "fieldName":"PRIMARYNONDIVIDEDURBAN",\r\n         "parentCellIndex":5,\r\n         "parentFieldName":"roadType"\r\n      },\r\n      {\r\n         "cellIndex":9,\r\n         "fieldName":"group",\r\n         "parentCellIndex":9,\r\n         "parentFieldName":"group"\r\n      }\r\n   ],\r\n   "mandateColumnMetaData":[\r\n      {\r\n         "cellIndex":1,\r\n         "fieldName":"receivedDate",\r\n         "parentCellIndex":1,\r\n         "parentFieldName":"receivedDate"\r\n      },\r\n      {\r\n         "cellIndex":2,\r\n         "fieldName":"workUnitId",\r\n         "parentCellIndex":2,\r\n         "parentFieldName":"workUnitId"\r\n      }\r\n   ]\r\n}', 'Info', NULL, NULL, NULL, '15001', NULL, NULL, NULL, 'InProgress', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '15001', '2022-11-01 00:00:00', '15001', '2022-11-01 00:00:00'),
	('ITAdmin', 'IT Admin', 'IT', 1, b'1', '{\r\n   "discardPercentage":1,\r\n   "skipRows":2,\r\n   "columnMetaData":[\r\n      {\r\n         "cellIndex":1,\r\n         "fieldName":"receivedDate",\r\n         "parentCellIndex":1,\r\n         "parentFieldName":"receivedDate"\r\n      },\r\n      {\r\n         "cellIndex":2,\r\n         "fieldName":"workUnitId",\r\n         "parentCellIndex":2,\r\n         "parentFieldName":"workUnitId"\r\n      },\r\n      {\r\n         "cellIndex":3,\r\n         "fieldName":"subCountry",\r\n         "parentCellIndex":3,\r\n         "parentFieldName":"subCountry"\r\n      },\r\n      {\r\n         "cellIndex":4,\r\n         "fieldName":"wuMiles",\r\n         "parentCellIndex":4,\r\n         "parentFieldName":"wuMiles"\r\n      },\r\n      {\r\n         "cellIndex":5,\r\n         "fieldName":"roadType",\r\n         "parentCellIndex":5,\r\n         "parentFieldName":"roadType"\r\n      },\r\n      {\r\n         "cellIndex":6,\r\n         "fieldName":"PRIMARYNONDIVIDEDMOTORWAYS",\r\n         "parentCellIndex":5,\r\n         "parentFieldName":"roadType"\r\n      },\r\n      {\r\n         "cellIndex":7,\r\n         "fieldName":"PRIMARYNONDIVIDEDTRUNK",\r\n         "parentCellIndex":5,\r\n         "parentFieldName":"roadType"\r\n      },\r\n      {\r\n         "cellIndex":8,\r\n         "fieldName":"PRIMARYNONDIVIDEDURBAN",\r\n         "parentCellIndex":5,\r\n         "parentFieldName":"roadType"\r\n      },\r\n      {\r\n         "cellIndex":9,\r\n         "fieldName":"group",\r\n         "parentCellIndex":9,\r\n         "parentFieldName":"group"\r\n      }\r\n   ],\r\n   "mandateColumnMetaData":[\r\n      {\r\n         "cellIndex":1,\r\n         "fieldName":"receivedDate",\r\n         "parentCellIndex":1,\r\n         "parentFieldName":"receivedDate"\r\n      },\r\n      {\r\n         "cellIndex":2,\r\n         "fieldName":"workUnitId",\r\n         "parentCellIndex":2,\r\n         "parentFieldName":"workUnitId"\r\n      }\r\n   ]\r\n}', 'Info', NULL, NULL, NULL, '15001', NULL, NULL, NULL, 'InProgress', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '15001', '2022-11-01 00:00:00', '15001', '2022-11-01 00:00:00'),
	('None', 'No Project', 'NODIVISION', 1, b'0', '{}', 'Info', NULL, NULL, NULL, '15001', NULL, NULL, NULL, 'InProgress', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '15001', '2022-11-01 00:00:00', '15001', '2022-11-01 00:00:00'),
	('NoProjectDEV', 'No Project', 'DEV', 1, b'1', '{\r\n   "columnMetaData":[\r\n      {\r\n	"cellIndex":0,\r\n	"fieldName":"slNo",\r\n	"parentCellIndex":0,\r\n        "parentFieldName":"slNo"\r\n      },\r\n      {\r\n         "cellIndex":1,\r\n         "fieldName":"receivedDate",\r\n         "parentCellIndex":1,\r\n         "parentFieldName":"receivedDate"\r\n      },\r\n      {\r\n         "cellIndex":2,\r\n         "fieldName":"group",\r\n         "parentCellIndex":2,\r\n         "parentFieldName":"group"\r\n      },\r\n      {\r\n         "cellIndex":3,\r\n         "fieldName":"project",\r\n         "parentCellIndex":3,\r\n         "parentFieldName":"project"\r\n      },\r\n      {\r\n         "cellIndex":4,\r\n         "fieldName":"workUnitId",\r\n         "parentCellIndex":4,\r\n         "parentFieldName":"workUnitId"\r\n      },\r\n      {\r\n         "cellIndex":5,\r\n         "fieldName":"subCountry",\r\n         "parentCellIndex":5,\r\n         "parentFieldName":"subCountry"\r\n      },\r\n      {\r\n         "cellIndex":6,\r\n         "fieldName":"wuMiles",\r\n         "parentCellIndex":6,\r\n         "parentFieldName":"wuMiles"\r\n      },\r\n      {\r\n         "cellIndex":7,\r\n         "fieldName":"remarks",\r\n         "parentCellIndex":7,\r\n         "parentFieldName":"remarks"\r\n      },\r\n      {\r\n         "cellIndex":8,\r\n         "fieldName":"roadType",\r\n         "parentCellIndex":8,\r\n         "parentFieldName":"roadType"\r\n      }\r\n   ],\r\n   "discardPercentage":1,\r\n   "mandateColumnMetaData":[\r\n      {\r\n         "cellIndex":1,\r\n         "fieldName":"receivedDate",\r\n         "parentCellIndex":1,\r\n         "parentFieldName":"receivedDate"\r\n      },\r\n      {\r\n         "cellIndex":4,\r\n         "fieldName":"workUnitId",\r\n         "parentCellIndex":4,\r\n         "parentFieldName":"workUnitId"\r\n      }\r\n   ],\r\n   "skipRows":2\r\n}', 'Info', NULL, NULL, NULL, '15001', NULL, NULL, NULL, 'InProgress', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '15001', '2022-11-01 00:00:00', '15001', '2022-11-01 00:00:00'),
	('NoProjectHR', 'No Project', 'HRAdmin', 1, b'1', '{\r\n   "columnMetaData":[\r\n      {\r\n	"cellIndex":0,\r\n	"fieldName":"slNo",\r\n	"parentCellIndex":0,\r\n        "parentFieldName":"slNo"\r\n      },\r\n      {\r\n         "cellIndex":1,\r\n         "fieldName":"receivedDate",\r\n         "parentCellIndex":1,\r\n         "parentFieldName":"receivedDate"\r\n      },\r\n      {\r\n         "cellIndex":2,\r\n         "fieldName":"group",\r\n         "parentCellIndex":2,\r\n         "parentFieldName":"group"\r\n      },\r\n      {\r\n         "cellIndex":3,\r\n         "fieldName":"project",\r\n         "parentCellIndex":3,\r\n         "parentFieldName":"project"\r\n      },\r\n      {\r\n         "cellIndex":4,\r\n         "fieldName":"workUnitId",\r\n         "parentCellIndex":4,\r\n         "parentFieldName":"workUnitId"\r\n      },\r\n      {\r\n         "cellIndex":5,\r\n         "fieldName":"subCountry",\r\n         "parentCellIndex":5,\r\n         "parentFieldName":"subCountry"\r\n      },\r\n      {\r\n         "cellIndex":6,\r\n         "fieldName":"wuMiles",\r\n         "parentCellIndex":6,\r\n         "parentFieldName":"wuMiles"\r\n      },\r\n      {\r\n         "cellIndex":7,\r\n         "fieldName":"remarks",\r\n         "parentCellIndex":7,\r\n         "parentFieldName":"remarks"\r\n      },\r\n      {\r\n         "cellIndex":8,\r\n         "fieldName":"roadType",\r\n         "parentCellIndex":8,\r\n         "parentFieldName":"roadType"\r\n      }\r\n   ],\r\n   "discardPercentage":1,\r\n   "mandateColumnMetaData":[\r\n      {\r\n         "cellIndex":1,\r\n         "fieldName":"receivedDate",\r\n         "parentCellIndex":1,\r\n         "parentFieldName":"receivedDate"\r\n      },\r\n      {\r\n         "cellIndex":4,\r\n         "fieldName":"workUnitId",\r\n         "parentCellIndex":4,\r\n         "parentFieldName":"workUnitId"\r\n      }\r\n   ],\r\n   "skipRows":2\r\n}', 'Info', NULL, NULL, NULL, '15001', NULL, NULL, NULL, 'InProgress', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '15001', '2022-11-01 00:00:00', '15001', '2022-11-01 00:00:00'),
	('NoProjectIT', 'No Project', 'IT', 1, b'1', '{\r\n   "columnMetaData":[\r\n      {\r\n	"cellIndex":0,\r\n	"fieldName":"slNo",\r\n	"parentCellIndex":0,\r\n        "parentFieldName":"slNo"\r\n      },\r\n      {\r\n         "cellIndex":1,\r\n         "fieldName":"receivedDate",\r\n         "parentCellIndex":1,\r\n         "parentFieldName":"receivedDate"\r\n      },\r\n      {\r\n         "cellIndex":2,\r\n         "fieldName":"group",\r\n         "parentCellIndex":2,\r\n         "parentFieldName":"group"\r\n      },\r\n      {\r\n         "cellIndex":3,\r\n         "fieldName":"project",\r\n         "parentCellIndex":3,\r\n         "parentFieldName":"project"\r\n      },\r\n      {\r\n         "cellIndex":4,\r\n         "fieldName":"workUnitId",\r\n         "parentCellIndex":4,\r\n         "parentFieldName":"workUnitId"\r\n      },\r\n      {\r\n         "cellIndex":5,\r\n         "fieldName":"subCountry",\r\n         "parentCellIndex":5,\r\n         "parentFieldName":"subCountry"\r\n      },\r\n      {\r\n         "cellIndex":6,\r\n         "fieldName":"wuMiles",\r\n         "parentCellIndex":6,\r\n         "parentFieldName":"wuMiles"\r\n      },\r\n      {\r\n         "cellIndex":7,\r\n         "fieldName":"remarks",\r\n         "parentCellIndex":7,\r\n         "parentFieldName":"remarks"\r\n      },\r\n      {\r\n         "cellIndex":8,\r\n         "fieldName":"roadType",\r\n         "parentCellIndex":8,\r\n         "parentFieldName":"roadType"\r\n      }\r\n   ],\r\n   "discardPercentage":1,\r\n   "mandateColumnMetaData":[\r\n      {\r\n         "cellIndex":1,\r\n         "fieldName":"receivedDate",\r\n         "parentCellIndex":1,\r\n         "parentFieldName":"receivedDate"\r\n      },\r\n      {\r\n         "cellIndex":4,\r\n         "fieldName":"workUnitId",\r\n         "parentCellIndex":4,\r\n         "parentFieldName":"workUnitId"\r\n      }\r\n   ],\r\n   "skipRows":2\r\n}', 'Info', NULL, NULL, NULL, '15001', NULL, NULL, NULL, 'InProgress', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '15001', '2022-11-01 00:00:00', '15001', '2022-11-01 00:00:00'),
	('ProFoc0001', 'Focus', 'IT', 1, b'1', NULL, 'Info', NULL, 'Stashook', NULL, '15235', NULL, NULL, NULL, 'InProgress', NULL, 'Online', 'Online', 'Text', NULL, NULL, NULL, NULL, '600', '3', '35', NULL, NULL, NULL, NULL, '15235', '2024-08-21 00:00:00', '15235', '2024-08-21 00:00:00');

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
